# Generated by Django 3.2.2 on 2021-05-09 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contactkeep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_save',
            field=models.DateTimeField(auto_now=True, verbose_name='Last saved on'),
        ),
        migrations.AddField(
            model_name='website',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 5, 9, 17, 42, 37, 915733, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='website',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, verbose_name='last visited on'),
        ),
    ]
