# Generated by Django 3.2.2 on 2021-05-10 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactkeep', '0002_auto_20210509_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Created on'),
        ),
    ]
