# Generated by Django 3.2.2 on 2021-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactkeep', '0003_alter_website_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Current Event'),
        ),
    ]
