# Generated by Django 3.2.2 on 2021-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactkeep', '0004_event_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='no name', max_length=250, verbose_name='Name for website'),
            preserve_default=False,
        ),
    ]
