# Generated by Django 3.2.2 on 2021-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactkeep', '0005_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='web_cache',
            field=models.CharField(default='', max_length=100000, verbose_name='Cache of website content'),
        ),
    ]
