# Generated by Django 3.2.2 on 2021-05-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactkeep', '0007_contact_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contactkeep.website'),
            preserve_default=False,
        ),
    ]
